import { wrap } from './utils';
import observedAttributesHelloworld from './components/hello-world/hello-world.observed-attributes';
import observedAttributesAsd from './components/asd/asd.observed-attributes';
import observedAttributesAsd from './components/asd/asd.observed-attributes';
import observedAttributesAsdQweZxc from './components/asd-qwe-zxc/asd-qwe-zxc.observed-attributes';
import observedAttributesAsdQweZxc from './components/asd-qwe-zxc/asd-qwe-zxc.observed-attributes';
import observedAttributesAsdQweZxc from './components/asd-qwe-zxc/asd-qwe-zxc.observed-attributes';
import observedAttributesHelloWorld from './components/hello-world/hello-world.observed-attributes';
import observedAttributesHelloWorld from './components/hello-world/hello-world.observed-attributes';
import observedAttributesHelloWorld from './components/hello-world/hello-world.observed-attributes';
import observedAttributesHelloWorld from './components/hello-world/hello-world.observed-attributes';
customElements.define('hello-world', wrap(()=>import('./components/hello-world/hello-world.component'), 'HelloWorld', observedAttributesHelloworld));customElements.define('asd', wrap(()=>import('./components/asd/asd.component'), 'Asd', observedAttributesAsd));
customElements.define('asd', wrap(()=>import('./components/asd/asd.component'), 'Asd', observedAttributesAsd));
customElements.define('asd-qwe-zxc', wrap(()=>import('./components/asd-qwe-zxc/asd-qwe-zxc.component'), 'AsdQweZxc', observedAttributesAsdQweZxc));
customElements.define('asd-qwe-zxc', wrap(()=>import('./components/asd-qwe-zxc/asd-qwe-zxc.component'), 'AsdQweZxc', observedAttributesAsdQweZxc));
customElements.define('asd-qwe-zxc', wrap(()=>import('./components/asd-qwe-zxc/asd-qwe-zxc.component'), 'AsdQweZxc', observedAttributesAsdQweZxc));
customElements.define('hello-world', wrap(()=>import('./components/hello-world/hello-world.component'), 'HelloWorld', observedAttributesHelloWorld));
customElements.define('hello-world', wrap(()=>import('./components/hello-world/hello-world.component'), 'HelloWorld', observedAttributesHelloWorld));
customElements.define('hello-world', wrap(()=>import('./components/hello-world/hello-world.component'), 'HelloWorld', observedAttributesHelloWorld));
customElements.define('hello-world', wrap(()=>import('./components/hello-world/hello-world.component'), 'HelloWorld', observedAttributesHelloWorld));
